version: "3.9"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: redis:latest

  celery:
    build: .
    command: celery -A chatible worker --loglevel=info
    volumes:
      - .:/code
    env_file:
      - ./.env
    depends_on:
      - web
      - redis
